port: 7880
bind_addresses:
  - "0.0.0.0"
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50050
  use_external_ip: false
  enable_loopback_candidate: true
room:
  auto_create: false
  empty_timeout: 1800
  departure_timeout: 60
logging:
  level: info
